/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Testament = IDL.Variant({ 'New' : IDL.Null, 'Old' : IDL.Null });
export const Verse = IDL.Record({ 'text' : IDL.Text, 'number' : IDL.Nat });
export const Chapter = IDL.Record({
  'verses' : IDL.Vec(Verse),
  'number' : IDL.Nat,
});
export const Book = IDL.Record({
  'name' : IDL.Text,
  'testament' : Testament,
  'chapters' : IDL.Vec(Chapter),
  'abbreviation' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'verse' : IDL.Nat,
  'book' : IDL.Text,
  'text' : IDL.Text,
  'chapter' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getBooksByTestament' : IDL.Func(
      [],
      [IDL.Vec(Book), IDL.Vec(Book)],
      ['query'],
    ),
  'getChapters' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
  'getVerse' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Verse], ['query']),
  'getVerses' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Verse)], ['query']),
  'searchVerses' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'seedBibleData' : IDL.Func([IDL.Vec(Book)], [], ['oneway']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Testament = IDL.Variant({ 'New' : IDL.Null, 'Old' : IDL.Null });
  const Verse = IDL.Record({ 'text' : IDL.Text, 'number' : IDL.Nat });
  const Chapter = IDL.Record({ 'verses' : IDL.Vec(Verse), 'number' : IDL.Nat });
  const Book = IDL.Record({
    'name' : IDL.Text,
    'testament' : Testament,
    'chapters' : IDL.Vec(Chapter),
    'abbreviation' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'verse' : IDL.Nat,
    'book' : IDL.Text,
    'text' : IDL.Text,
    'chapter' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getBooksByTestament' : IDL.Func(
        [],
        [IDL.Vec(Book), IDL.Vec(Book)],
        ['query'],
      ),
    'getChapters' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
    'getVerse' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Verse], ['query']),
    'getVerses' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Verse)], ['query']),
    'searchVerses' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'seedBibleData' : IDL.Func([IDL.Vec(Book)], [], ['oneway']),
  });
};

export const init = ({ IDL }) => { return []; };