/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'name' : string,
  'testament' : Testament,
  'chapters' : Array<Chapter>,
  'abbreviation' : string,
}
export interface Chapter { 'verses' : Array<Verse>, 'number' : bigint }
export interface SearchResult {
  'verse' : bigint,
  'book' : string,
  'text' : string,
  'chapter' : bigint,
}
export type Testament = { 'New' : null } |
  { 'Old' : null };
export interface Verse { 'text' : string, 'number' : bigint }
export interface _SERVICE {
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getBook' : ActorMethod<[string], [] | [Book]>,
  'getBooksByTestament' : ActorMethod<[], [Array<Book>, Array<Book>]>,
  'getChapters' : ActorMethod<[string], Array<Chapter>>,
  'getVerse' : ActorMethod<[string, bigint, bigint], Verse>,
  'getVerses' : ActorMethod<[string, bigint], Array<Verse>>,
  'searchVerses' : ActorMethod<[string], Array<SearchResult>>,
  'seedBibleData' : ActorMethod<[Array<Book>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];