/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Verse {
    text: string;
    number: bigint;
}
export interface SearchResult {
    verse: bigint;
    book: string;
    text: string;
    chapter: bigint;
}
export interface Book {
    name: string;
    testament: Testament;
    chapters: Array<Chapter>;
    abbreviation: string;
}
export interface Chapter {
    verses: Array<Verse>;
    number: bigint;
}
export enum Testament {
    New = "New",
    Old = "Old"
}
export interface backendInterface {
    getAllBooks(): Promise<Array<Book>>;
    getBook(abbreviation: string): Promise<Book | null>;
    getBooksByTestament(): Promise<[Array<Book>, Array<Book>]>;
    getChapters(bookAbbreviation: string): Promise<Array<Chapter>>;
    getVerse(bookAbbreviation: string, chapterNumber: bigint, verseNumber: bigint): Promise<Verse>;
    getVerses(bookAbbreviation: string, chapterNumber: bigint): Promise<Array<Verse>>;
    searchVerses(keyword: string): Promise<Array<SearchResult>>;
    seedBibleData(kjvBooks: Array<Book>): Promise<void>;
}
import type { Book as _Book, Chapter as _Chapter, Testament as _Testament } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBook(arg0: string): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooksByTestament(): Promise<[Array<Book>, Array<Book>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooksByTestament();
                return [
                    from_candid_vec_n1(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n1(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooksByTestament();
            return [
                from_candid_vec_n1(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n1(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getChapters(arg0: string): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapters(arg0);
            return result;
        }
    }
    async getVerse(arg0: string, arg1: bigint, arg2: bigint): Promise<Verse> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerse(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerse(arg0, arg1, arg2);
            return result;
        }
    }
    async getVerses(arg0: string, arg1: bigint): Promise<Array<Verse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerses(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerses(arg0, arg1);
            return result;
        }
    }
    async searchVerses(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVerses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVerses(arg0);
            return result;
        }
    }
    async seedBibleData(arg0: Array<Book>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedBibleData(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedBibleData(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Book_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Book {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Testament_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testament): Testament {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Book]): Book | null {
    return value.length === 0 ? null : from_candid_Book_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    testament: _Testament;
    chapters: Array<_Chapter>;
    abbreviation: string;
}): {
    name: string;
    testament: Testament;
    chapters: Array<Chapter>;
    abbreviation: string;
} {
    return {
        name: value.name,
        testament: from_candid_Testament_n4(_uploadFile, _downloadFile, value.testament),
        chapters: value.chapters,
        abbreviation: value.abbreviation
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Old: null;
}): Testament {
    return "New" in value ? Testament.New : "Old" in value ? Testament.Old : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Array<Book> {
    return value.map((x)=>from_candid_Book_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Book_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Book): _Book {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Testament_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Testament): _Testament {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    testament: Testament;
    chapters: Array<Chapter>;
    abbreviation: string;
}): {
    name: string;
    testament: _Testament;
    chapters: Array<_Chapter>;
    abbreviation: string;
} {
    return {
        name: value.name,
        testament: to_candid_Testament_n10(_uploadFile, _downloadFile, value.testament),
        chapters: value.chapters,
        abbreviation: value.abbreviation
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Testament): {
    New: null;
} | {
    Old: null;
} {
    return value == Testament.New ? {
        New: null
    } : value == Testament.Old ? {
        Old: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Book>): Array<_Book> {
    return value.map((x)=>to_candid_Book_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
